### ISSUE TITLE
SCP-RU API

### ISSUE THREAD

**Issue by resure** [mohaxspb/ScpFoundationRu#41]
Привет, я администратор scpfoundation.ru & .net.

Некоторое время назад я обнаружил, что вы используете наши не публичные API в своем приложении и что даже пару раз уже спотыкались, когда мы тем или иным образом их меняли.  Это не ок. Приходите к нам в [чат](https://discord.gg/Hg28mbR), обсудим, что и как вы используете и сделаем для вас стабильное публичное апи, чтобы пользователи больше не страдали.
В текущем виде мы можем предоставить вам базовые функции (вроде того, что вы уже используете: случайная страница, поиск по тегам), а если вы в будущем переведете свой проект на нормальную oss-лицензию, то список возможностей расширим.

**Comment by NevaSpbRx** [comment]
Привет!
Извини за долгий ответ. Были задействованы в подготовки стенда для бигфеста.
Да, с удовольствием пообщаемся, скорее всего у нас будет возможность выйти
на связь завтра вечером, после 21.00.
Есть вопрос. Можем ли мы пообщаться в "телеграм" или хотя б в скайпе?

9 июня 2017 г., 23:16 пользователь Gadzhi Gadzhiev <notifications@github.com

**Comment by resure** [comment]
Telegram — самое то.
t.me/resure

**Comment by resure** [comment]
Обсудили в телеграме, по результатам постараюсь на этой неделе завести тикеты.
